### ISSUE TITLE
HTTP 429 error with OpenStreetMap.org 

### ISSUE THREAD

**Issue by arky** [noffle/tile-dl#2]
Using tile-dl with openstreetmap.org fails with 429 error. I guess making too many request in short interval trips their rate limiting feature?

```shell
$ cat  url_template
https://c.tile.openstreetmap.org/{z}/{x}/{y}.png

$ tile-dl -t "$(cat url_template)" --lon=-122.2632601 --lat=37.8027446 --radius 0.1 --zoom 12 --output tiles/{z}/{x}/{y}.png
This will make 16 HTTP requests. Proceed? [y/N] y
GET 655 1581 12 https://c.tile.openstreetmap.org/12/655/1581.png
GET 656 1581 12 https://c.tile.openstreetmap.org/12/656/1581.png
GET 657 1581 12 https://c.tile.openstreetmap.org/12/657/1581.png
GET 658 1581 12 https://c.tile.openstreetmap.org/12/658/1581.png
GET 655 1582 12 https://c.tile.openstreetmap.org/12/655/1582.png
GET 656 1582 12 https://c.tile.openstreetmap.org/12/656/1582.png
GET 657 1582 12 https://c.tile.openstreetmap.org/12/657/1582.png
GET 658 1582 12 https://c.tile.openstreetmap.org/12/658/1582.png
GET 655 1583 12 https://c.tile.openstreetmap.org/12/655/1583.png
GET 656 1583 12 https://c.tile.openstreetmap.org/12/656/1583.png
GET 657 1583 12 https://c.tile.openstreetmap.org/12/657/1583.png
GET 658 1583 12 https://c.tile.openstreetmap.org/12/658/1583.png
GET 655 1584 12 https://c.tile.openstreetmap.org/12/655/1584.png
GET 656 1584 12 https://c.tile.openstreetmap.org/12/656/1584.png
GET 657 1584 12 https://c.tile.openstreetmap.org/12/657/1584.png
GET 658 1584 12 https://c.tile.openstreetmap.org/12/658/1584.png
/usr/lib/node_modules/tile-dl/bin/cmd.js:53
     if (err) throw err
              ^
Error: status 429
   at ClientRequest.<anonymous> (/usr/lib/node_modules/tile-dl/bin/cmd.js:67:43)
   at Object.onceWrapper (events.js:315:30)
   at emitOne (events.js:116:13)
   at ClientRequest.emit (events.js:211:7)
   at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:552:21)
   at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
   at TLSSocket.socketOnData (_http_client.js:454:20)
   at emitOne (events.js:116:13)
   at TLSSocket.emit (events.js:211:7)
   at addChunk (_stream_readable.js:263:12) 

```

**Comment by hackergrrl** [comment]
Sounds like it. HTTP 429 is `Too Many Requests`. I'm not sure there's anything that can be done by `tile-dl` to change this.

**Comment by arky** [comment]
Thanks @noffle Closing this bug as resolved/invalid.

**Comment by gmaclennan** [comment]
Some http request libraries will retry on a `429` response, if possible using the `Retry-After` header. [got](https://github.com/sindresorhus/got) would do this, could be swapped in for the current way requests are done.
